---
- name: Password Generator
  hosts: localhost
  user: lancom
  become: True
  connection: local
  tasks:
    - name: Ensure pwgen is installed
      apt:
        name: pwgen
        state: present

    - name: Generate Password
      shell: pwgen -s 8 1 -v -c -0
      register: mypass

    - name: Print the generated password
      debug:
        msg: "The password is {{ mypass.stdout }}"


- name: Connect to AP
  hosts: [ciscoaps]
  gather_facts: false
  connection: local

  vars:
    ssh_auth:
      username: usertr
      password: "123"
      auth_pass: "123"
      authorize: yes

  tasks:
    - name: Change WPA-2 PSK
      ios_config:
        provider: "{{ ssh_auth }}"
        lines: "wpa-psk ascii 0 {{ hostvars['localhost']['mypass']['stdout'] }}"
        parents: dot11 ssid TEST_PORTAL
        save_when: modified

      register: print_output

    - debug: var=print_output


- name: Connect Localhost
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Send Email
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        secure: starttls
        username: testansiblemail@gmail.com
        password: *********
        to: Mike Trih <trixasmixas@gmail.com>
        subject: "Αλλαγή Κωδικού WIFI (WPA2)"
        body: "Ο νέος σας κωδικός για πρόσβαση στο wifi είναι {{ hostvars['localhost']['mypass']['stdout'] }}

      register: print_output


...
