#Call with ansible-playbook -e "ip_addr={Peer VPN ip address (i.e. 10.10.10.2/32)} public_key={Peer public key}" wireguard-peer.yml
---
- name: Add Peer
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Adding peer to wg0.conf
      lineinfile:
        path: /etc/wireguard/wg0.conf
        line: |

          [Peer]
          PublicKey = {{ public_key }}
          AllowedIPs = {{ ip_addr }}

    - name: Restart wireguard (wg0.conf)
      shell: |
        wg-quick down wg0
        wg-quick up wg0
---
#Client config file:
# [Interface]
# PrivateKey = 4CeXPt1sccFYH/YhAND0aotH1/sue4xgpRE9EzhcU0M=

# [Peer]
# PublicKey = 9t7RTnpmyL+6yek5hvQSOGVPfDB1r8W8KTq9GxFNzwQ=
# AllowedIPs = 0.0.0.0/0
# Endpoint = 192.168.2.14:51820 (server ip)
# PersistentKeepalive = 21

