# Call with ansible-playbook -e "user={peer username (i.e. mixalis)} revoke={yes or no}" wireguard-peer-revoke.yml
---
- name: Revoke {{ user }}
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Find {{ user }} in server configuration (1)
      shell: cat /etc/wireguard/wg0.conf | grep -A 3 "#{{ user }}" | tail -1 | cut -d "#" -f2
      register: ipaddress

    - name: Find {{ user }} in server configuration (2)
      shell: cat /etc/wireguard/wg0.conf | grep -A 2 "#{{ user }}" | tail -1 | cut -d "#" -f2
      register: publickey

    - name: Revoke {{ user }}
      replace:
        path: /etc/wireguard/wg0.conf
        regexp: |
          #{{ user }}
          \[Peer\]
          {{ publickey.stdout | regex_escape() }}
          {{ ipaddress.stdout }}
        replace: |
          #{{ user }}
          #[Peer]
          #{{ publickey.stdout }}
          #{{ ipaddress.stdout }}
      when: revoke == "yes"

    - name: Unrevoke {{ user }}
      replace:
        path: /etc/wireguard/wg0.conf
        regexp: |
          #{{ user }}
          #\[Peer\]
          #{{ publickey.stdout | regex_escape() }}
          #{{ ipaddress.stdout }}
        replace: |
          #{{ user }}
          [Peer]
          {{ publickey.stdout }}
          {{ ipaddress.stdout }}
      when: revoke == "no"

    - name: Restart wireguard (wg0.conf)
      shell: |
        wg-quick down wg0
        wg-quick up wg0

...
